export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ORDER_MANAGER: 'ORDER_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  CONTENT_MANAGER: 'CONTENT_MANAGER',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  CUSTOMER: 'CUSTOMER',
} as const;

export type RoleType = keyof typeof ROLES;

export const ADMIN_ROLES: RoleType[] = [
  'SUPER_ADMIN',
  'ADMIN',
  'ORDER_MANAGER',
  'INVENTORY_MANAGER',
  'CONTENT_MANAGER',
  'CUSTOMER_SUPPORT',
];

export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  REFUNDED: 'REFUNDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
} as const;

// Valid order status transitions state machine
export const VALID_ORDER_TRANSITIONS: Record<string, string[]> = {
  PENDING: ['AWAITING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'PAYMENT_FAILED'],
  AWAITING_PAYMENT: ['CONFIRMED', 'PAYMENT_FAILED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'CANCELLATION_REQUESTED', 'CANCELLED'],
  PROCESSING: ['PACKED', 'CANCELLATION_REQUESTED', 'CANCELLED'],
  PACKED: ['SHIPPED', 'CANCELLED'],
  SHIPPED: ['OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED'],
  OUT_FOR_DELIVERY: ['DELIVERED', 'RETURNED'],
  DELIVERED: ['REFUND_PENDING'],
  CANCELLATION_REQUESTED: ['CANCELLED', 'PROCESSING'],
  CANCELLED: ['REFUND_PENDING'],
  REFUND_PENDING: ['PARTIALLY_REFUNDED', 'REFUNDED'],
  PARTIALLY_REFUNDED: ['REFUNDED'],
  REFUNDED: [],
  PAYMENT_FAILED: ['AWAITING_PAYMENT', 'CANCELLED'],
};

export const DEFAULT_PAGE_SIZE = 12;
export const MAX_PAGE_SIZE = 100;
